### ISSUE TITLE
Port to intranet search

### ISSUE THREAD

**Issue by martent** [malmostad/sitesearch#4]
Port the external search app with editors recommendation to the intranet. The current site search embedded in the Dashboard will be removed when this app is in production and stable.

OAuth2 will be used for the intranet version in the same way as for the external one.

cc @jesperbylund

**Comment by magnivar** [comment]
@olajoh1  läs och utvärdera
INC-324150	Åtkomstproblem KominSök (Direct Access-relaterat?)

**Comment by magnivar** [comment]
Åtkomstproblem var DirectAccessberoende och är löst.
