### ISSUE TITLE
Server svarar inte

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitesearch#8]
Regelmässigt under de senaste veckorna svarar inte s2.malmo.se (kominsök) vid anrop. 

![image](https://cloud.githubusercontent.com/assets/6176181/19466947/bc4266dc-950e-11e6-8308-f433aed64620.png)

**Comment by martent** [comment]
Jag kunde inte upprepa felet men jag såg att serverns logg-hantering hängt sig. Kan du testa om det fungerar nu (det funkar via VPN).

cc: @magnivar

**Comment by olajoh1** [comment]
Fungerar just nu.

**Comment by martent** [comment]
Problemet med servern åtgärdades 18/10.
